#cloud-config

# Mettre le bon timezone
timezone: Europe/Paris

# Créer un utilisateur (ubuntu)
users:
- name: ubuntu
  gecos: Ubuntu User
  shell: /bin/bash
  home: /home/ubuntu
  groups: users,admin,wheel,lxd,docker
  sudo: ALL=(ALL) NOPASSWD:ALL

# Update et upgrade
package_update: true
package_upgrade: true

# Installation des packages nécessaire (uidmap pour docker rootless)
packages:
  - apt-transport-https
  - bash-completion
  - ca-certificates
  - curl
  - git
  - uidmap

runcmd:
  # Connexion avec mdp via vscode
  - sudo sed -i 's/no/Yes/g' /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
  - sudo service ssh restart
  - echo 'ubuntu:soso' | chpasswd
  # Installation de Docker
  - curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh
  - curl -fsSL https://get.docker.com/rootless --force | sh
  - systemctl start docker
  - systemctl enable docker
  # - docker run -d --name mynginxserver -p 8080:80 nginx:alpine-slim
